'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizedText
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MPIClient.LocalizedText", GetType(LocalizedText).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed..
        '''</summary>
        Friend Shared ReadOnly Property STATUS_COMPLETED() As String
            Get
                Return ResourceManager.GetString("STATUS_COMPLETED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error..
        '''</summary>
        Friend Shared ReadOnly Property STATUS_Error() As String
            Get
                Return ResourceManager.GetString("STATUS_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Synchronizing....
        '''</summary>
        Friend Shared ReadOnly Property STATUS_Synchronizing() As String
            Get
                Return ResourceManager.GetString("STATUS_Synchronizing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to enroll new patient?.
        '''</summary>
        Friend Shared ReadOnly Property STR_AreYouSureYouWantToEnrollNewPatient() As String
            Get
                Return ResourceManager.GetString("STR_AreYouSureYouWantToEnrollNewPatient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to exit?.
        '''</summary>
        Friend Shared ReadOnly Property STR_AreYouSureYouWantToExit() As String
            Get
                Return ResourceManager.GetString("STR_AreYouSureYouWantToExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to At least two fingerprints are required for the enrollment..
        '''</summary>
        Friend Shared ReadOnly Property STR_AtLeastTwoFingerprintsAreRequiredForTheEnrollment() As String
            Get
                Return ResourceManager.GetString("STR_AtLeastTwoFingerprintsAreRequiredForTheEnrollment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property STR_CANCEL() As String
            Get
                Return ResourceManager.GetString("STR_CANCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can&apos;t connect to the server. You&apos;re offline..
        '''</summary>
        Friend Shared ReadOnly Property STR_CantConnectToTheServerYoureOffline() As String
            Get
                Return ResourceManager.GetString("STR_CantConnectToTheServerYoureOffline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmation.
        '''</summary>
        Friend Shared ReadOnly Property STR_Confirmation() As String
            Get
                Return ResourceManager.GetString("STR_Confirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property STR_Error() As String
            Get
                Return ResourceManager.GetString("STR_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while saving!!!.
        '''</summary>
        Friend Shared ReadOnly Property STR_ErrorWhileSaving() As String
            Get
                Return ResourceManager.GetString("STR_ErrorWhileSaving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while serializing JSON object..
        '''</summary>
        Friend Shared ReadOnly Property STR_ErrorWhileSerializingJSONObject() As String
            Get
                Return ResourceManager.GetString("STR_ErrorWhileSerializingJSONObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fail in synchronizing data in local database..
        '''</summary>
        Friend Shared ReadOnly Property STR_FailInSynchronizingDataInLocalDatabase() As String
            Get
                Return ResourceManager.GetString("STR_FailInSynchronizingDataInLocalDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fail in updating patient..
        '''</summary>
        Friend Shared ReadOnly Property STR_FailInUpdatingPatient() As String
            Get
                Return ResourceManager.GetString("STR_FailInUpdatingPatient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fingerprint scanner initialized Successfull..
        '''</summary>
        Friend Shared ReadOnly Property STR_FingerprintScannerInitializedSuccessfull() As String
            Get
                Return ResourceManager.GetString("STR_FingerprintScannerInitializedSuccessfull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fingerprint scanner is unplugged..
        '''</summary>
        Friend Shared ReadOnly Property STR_FingerprintScannerIsUnplugged() As String
            Get
                Return ResourceManager.GetString("STR_FingerprintScannerIsUnplugged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to - Gender must be selected..
        '''</summary>
        Friend Shared ReadOnly Property STR_GenderMustBeSelected() As String
            Get
                Return ResourceManager.GetString("STR_GenderMustBeSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bad.
        '''</summary>
        Friend Shared ReadOnly Property STR_IMAGE_BAD_QUALITY() As String
            Get
                Return ResourceManager.GetString("STR_IMAGE_BAD_QUALITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hight.
        '''</summary>
        Friend Shared ReadOnly Property STR_IMAGE_HIGHT_QUALITY() As String
            Get
                Return ResourceManager.GetString("STR_IMAGE_HIGHT_QUALITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Medium.
        '''</summary>
        Friend Shared ReadOnly Property STR_IMAGE_MEDIUM_QUALITY() As String
            Get
                Return ResourceManager.GetString("STR_IMAGE_MEDIUM_QUALITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information.
        '''</summary>
        Friend Shared ReadOnly Property STR_Information() As String
            Get
                Return ResourceManager.GetString("STR_Information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offline.
        '''</summary>
        Friend Shared ReadOnly Property STR_Offline() As String
            Get
                Return ResourceManager.GetString("STR_Offline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to - One fingerprint is required..
        '''</summary>
        Friend Shared ReadOnly Property STR_OneFingerprintIsRequired() As String
            Get
                Return ResourceManager.GetString("STR_OneFingerprintIsRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Online.
        '''</summary>
        Friend Shared ReadOnly Property STR_Online() As String
            Get
                Return ResourceManager.GetString("STR_Online", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  patients found..
        '''</summary>
        Friend Shared ReadOnly Property STR_PatientsFound() As String
            Get
                Return ResourceManager.GetString("STR_PatientsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  records found.
        '''</summary>
        Friend Shared ReadOnly Property STR_RecordsFound() As String
            Get
                Return ResourceManager.GetString("STR_RecordsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to - Some fingerprints are in bad quality (Medium to hight quality is required)..
        '''</summary>
        Friend Shared ReadOnly Property STR_SomeFingerprintsAreInBadQualityMediumToHightQual() As String
            Get
                Return ResourceManager.GetString("STR_SomeFingerprintsAreInBadQualityMediumToHightQual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to - Some fingerprints are the same..
        '''</summary>
        Friend Shared ReadOnly Property STR_SomeFingerprintsAreTheSame() As String
            Get
                Return ResourceManager.GetString("STR_SomeFingerprintsAreTheSame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: scaning finger.
        '''</summary>
        Friend Shared ReadOnly Property STR_StatusFingerPlaced() As String
            Get
                Return ResourceManager.GetString("STR_StatusFingerPlaced", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Ready.
        '''</summary>
        Friend Shared ReadOnly Property STR_StatusReady() As String
            Get
                Return ResourceManager.GetString("STR_StatusReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status: Unplugged.
        '''</summary>
        Friend Shared ReadOnly Property STR_StatusUnplugged() As String
            Get
                Return ResourceManager.GetString("STR_StatusUnplugged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully save with PatientID = .
        '''</summary>
        Friend Shared ReadOnly Property STR_SuccessfullySaveWithPatientID() As String
            Get
                Return ResourceManager.GetString("STR_SuccessfullySaveWithPatientID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully save with VistiID = .
        '''</summary>
        Friend Shared ReadOnly Property STR_SuccessfullySaveWithVistiID() As String
            Get
                Return ResourceManager.GetString("STR_SuccessfullySaveWithVistiID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successful update..
        '''</summary>
        Friend Shared ReadOnly Property STR_SuccessfulUpdate() As String
            Get
                Return ResourceManager.GetString("STR_SuccessfulUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The request was aborted: The request was canceled.
        '''</summary>
        Friend Shared ReadOnly Property STR_TheRequestWasAbortedTheRequestWasCanceled() As String
            Get
                Return ResourceManager.GetString("STR_TheRequestWasAbortedTheRequestWasCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The WebServer encounter problem: {0} Status: Server Error.
        '''</summary>
        Friend Shared ReadOnly Property STR_TheWebServerEncounterProblemStatusServerError() As String
            Get
                Return ResourceManager.GetString("STR_TheWebServerEncounterProblemStatusServerError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning.
        '''</summary>
        Friend Shared ReadOnly Property STR_Warning() As String
            Get
                Return ResourceManager.GetString("STR_Warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Webserver: Internal server error..
        '''</summary>
        Friend Shared ReadOnly Property STR_WebserverInternalServerError() As String
            Get
                Return ResourceManager.GetString("STR_WebserverInternalServerError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
